// Generated by gencpp from file pick_n_delivery/NewGoal.msg
// DO NOT EDIT!


#ifndef PICK_N_DELIVERY_MESSAGE_NEWGOAL_H
#define PICK_N_DELIVERY_MESSAGE_NEWGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_n_delivery
{
template <class ContainerAllocator>
struct NewGoal_
{
  typedef NewGoal_<ContainerAllocator> Type;

  NewGoal_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  NewGoal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::pick_n_delivery::NewGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_n_delivery::NewGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NewGoal_

typedef ::pick_n_delivery::NewGoal_<std::allocator<void> > NewGoal;

typedef boost::shared_ptr< ::pick_n_delivery::NewGoal > NewGoalPtr;
typedef boost::shared_ptr< ::pick_n_delivery::NewGoal const> NewGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_n_delivery::NewGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_n_delivery::NewGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_n_delivery::NewGoal_<ContainerAllocator1> & lhs, const ::pick_n_delivery::NewGoal_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_n_delivery::NewGoal_<ContainerAllocator1> & lhs, const ::pick_n_delivery::NewGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_n_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_n_delivery::NewGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_n_delivery::NewGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_n_delivery::NewGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::pick_n_delivery::NewGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa130bc60ee651385ULL;
  static const uint64_t static_value2 = 0x5dc62ea83fcc5b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_n_delivery/NewGoal";
  }

  static const char* value(const ::pick_n_delivery::NewGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
;
  }

  static const char* value(const ::pick_n_delivery::NewGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NewGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_n_delivery::NewGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_n_delivery::NewGoal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_N_DELIVERY_MESSAGE_NEWGOAL_H
